

# -----------------------------------------------------------------------Image list creation --------------------------------------------------------------


#                            Biodiversidad de especies de aves presentes en el territorio del departamento de Cundinamarca en Colombia.


#                            Número de especies de la familia Accipitridae (halcones) incluidas en la lista: 22 taxones

#                            Número de especies de la familia Trochilidae (Colibríes) incluidas en la lista: 75 taxones



# -------------------------------------------------------------------------- Data sources -----------------------------------------------------------------


#                                   * Global Biodiversity Information Facility, GBIF. API 
#                                   * libro: Gobernación de Cundinamarca. Colibríes de Cundinamarca. Bogotá. 2018.
#                                   * Wikipedia


# ----------------------------------------------------------------------------------------------------------------------------------------------------------




BirdCipher_list = [["C:/BirdCipher/Bird_images/Struthioniformes1.png", "C:/BirdCipher/Bird_images/Struthioniformes2.png",
"C:/BirdCipher/Bird_images/Struthioniformes3.png", "C:/BirdCipher/Bird_images/Struthioniformes4.png",
"C:/BirdCipher/Bird_images/Struthioniformes5.png", "C:/BirdCipher/Bird_images/Struthioniformes6.png"], 
["C:/BirdCipher/Bird_images/Tinamiformes1.png", "C:/BirdCipher/Bird_images/Tinamiformes2.png", 
"C:/BirdCipher/Bird_images/Tinamiformes3.png", "C:/BirdCipher/Bird_images/Tinamiformes4.png", "C:/BirdCipher/Bird_images/Tinamiformes5.png",
"C:/BirdCipher/Bird_images/Tinamiformes6.png",], ["C:/BirdCipher/Bird_images/Rheiformes1.png", "C:/BirdCipher/Bird_images/Rheiformes2.png",
"C:/BirdCipher/Bird_images/Rheiformes3.png", "C:/BirdCipher/Bird_images/Rheiformes4.png", "C:/BirdCipher/Bird_images/Rheiformes5.png",
"C:/BirdCipher/Bird_images/Rheiformes6.png", "C:/BirdCipher/Bird_images/Rheiformes7.png"], ["C:/BirdCipher/Bird_images/Apterygiformes1.png",
"C:/BirdCipher/Bird_images/Apterygiformes2.png", "C:/BirdCipher/Bird_images/Apterygiformes3.png", "C:/BirdCipher/Bird_images/Apterygiformes4.png",
"C:/BirdCipher/Bird_images/Apterygiformes5.png", "C:/BirdCipher/Bird_images/Apterygiformes6.png", "C:/BirdCipher/Bird_images/Apterygiformes7.png"],
["C:/BirdCipher/Bird_images/Casuariiformes1.png", "C:/BirdCipher/Bird_images/Casuariiformes2.png", "C:/BirdCipher/Bird_images/Casuariiformes3.png",
"C:/BirdCipher/Bird_images/Casuariiformes4.png", "C:/BirdCipher/Bird_images/Casuariiformes5.png", "C:/BirdCipher/Bird_images/Casuariiformes6.png",
"C:/BirdCipher/Bird_images/Casuariiformes7.png"], ["C:/BirdCipher/Bird_images/Galliformes1.png", "C:/BirdCipher/Bird_images/Galliformes2.png",
"C:/BirdCipher/Bird_images/Galliformes3.png", "C:/BirdCipher/Bird_images/Galliformes4.png", "C:/BirdCipher/Bird_images/Galliformes5.png",
"C:/BirdCipher/Bird_images/Galliformes6.png", "C:/BirdCipher/Bird_images/Galliformes7.png", "C:/BirdCipher/Bird_images/Galliformes8.png",
"C:/BirdCipher/Bird_images/Galliformes9.png", "C:/BirdCipher/Bird_images/Galliformes10.png", "C:/BirdCipher/Bird_images/Galliformes11.png",
"C:/BirdCipher/Bird_images/Galliformes12.png", "C:/BirdCipher/Bird_images/Galliformes13.png", "C:/BirdCipher/Bird_images/Galliformes14.png",
"C:/BirdCipher/Bird_images/Galliformes15.png"], ["C:/BirdCipher/Bird_images/Anseriformes1.png", "C:/BirdCipher/Bird_images/Anseriformes2.png",
"C:/BirdCipher/Bird_images/Anseriformes3.png", "C:/BirdCipher/Bird_images/Anseriformes4.png", "C:/BirdCipher/Bird_images/Anseriformes5.png",
"C:/BirdCipher/Bird_images/Anseriformes6.png", "C:/BirdCipher/Bird_images/Anseriformes7.png", "C:/BirdCipher/Bird_images/Anseriformes8.png",
"C:/BirdCipher/Bird_images/Anseriformes9.png", "C:/BirdCipher/Bird_images/Anseriformes10.png", "C:/BirdCipher/Bird_images/Anseriformes11.png",
"C:/BirdCipher/Bird_images/Anseriformes12.png"], ["C:/BirdCipher/Bird_images/Phoenicopteriformes1.png", "C:/BirdCipher/Bird_images/Phoenicopteriformes2.png",
"C:/BirdCipher/Bird_images/Phoenicopteriformes3.png", "C:/BirdCipher/Bird_images/Phoenicopteriformes4.png", "C:/BirdCipher/Bird_images/Phoenicopteriformes5.png",
"C:/BirdCipher/Bird_images/Phoenicopteriformes6.png", "C:/BirdCipher/Bird_images/Phoenicopteriformes7.png", "C:/BirdCipher/Bird_images/Phoenicopteriformes8.png",
"C:/BirdCipher/Bird_images/Phoenicopteriformes9.png"], ["C:/BirdCipher/Bird_images/Podicipediformes1.png", "C:/BirdCipher/Bird_images/Podicipediformes2.png",
"C:/BirdCipher/Bird_images/Podicipediformes3.png", "C:/BirdCipher/Bird_images/Podicipediformes4.png", "C:/BirdCipher/Bird_images/Podicipediformes5.png",
"C:/BirdCipher/Bird_images/Podicipediformes6.png", "C:/BirdCipher/Bird_images/Podicipediformes7.png", "C:/BirdCipher/Bird_images/Podicipediformes8.png",
"C:/BirdCipher/Bird_images/Podicipediformes9.png", "C:/BirdCipher/Bird_images/Podicipediformes10.png", "C:/BirdCipher/Bird_images/Podicipediformes11.png",
"C:/BirdCipher/Bird_images/Podicipediformes12.png"], ["C:/BirdCipher/Bird_images/Columbiformes1.png", "C:/BirdCipher/Bird_images/Columbiformes2.png",
"C:/BirdCipher/Bird_images/Columbiformes3.png", "C:/BirdCipher/Bird_images/Columbiformes4.png", "C:/BirdCipher/Bird_images/Columbiformes5.png",
"C:/BirdCipher/Bird_images/Columbiformes6.png", "C:/BirdCipher/Bird_images/Columbiformes7.png", "C:/BirdCipher/Bird_images/Columbiformes8.png",
"C:/BirdCipher/Bird_images/Columbiformes9.png", "C:/BirdCipher/Bird_images/Columbiformes10.png", "C:/BirdCipher/Bird_images/Columbiformes11.png",
"C:/BirdCipher/Bird_images/Columbiformes12.png", "C:/BirdCipher/Bird_images/Columbiformes13.png", "C:/BirdCipher/Bird_images/Columbiformes14.png",
"C:/BirdCipher/Bird_images/Columbiformes15.png", "C:/BirdCipher/Bird_images/Columbiformes16.png"], ["C:/BirdCipher/Bird_images/Mesitornithidae1.png",
"C:/BirdCipher/Bird_images/Mesitornithidae2.png", "C:/BirdCipher/Bird_images/Mesitornithidae3.png", "C:/BirdCipher/Bird_images/Mesitornithidae4.png",
"C:/BirdCipher/Bird_images/Mesitornithidae5.png", "C:/BirdCipher/Bird_images/Mesitornithidae6.png", "C:/BirdCipher/Bird_images/Mesitornithidae7.png",
"C:/BirdCipher/Bird_images/Mesitornithidae8.png", "C:/BirdCipher/Bird_images/Mesitornithidae9.png", "C:/BirdCipher/Bird_images/Mesitornithidae10.png",
"C:/BirdCipher/Bird_images/Mesitornithidae11.png"], ["C:/BirdCipher/Bird_images/Pterocliformes1.png", "C:/BirdCipher/Bird_images/Pterocliformes2.png",
"C:/BirdCipher/Bird_images/Pterocliformes3.png", "C:/BirdCipher/Bird_images/Pterocliformes4.png", "C:/BirdCipher/Bird_images/Pterocliformes5.png",
"C:/BirdCipher/Bird_images/Pterocliformes6.png", "C:/BirdCipher/Bird_images/Pterocliformes7.png", "C:/BirdCipher/Bird_images/Pterocliformes8.png",
"C:/BirdCipher/Bird_images/Pterocliformes9.png", "C:/BirdCipher/Bird_images/Pterocliformes10.png", "C:/BirdCipher/Bird_images/Pterocliformes11.png",
"C:/BirdCipher/Bird_images/Pterocliformes12.png", "C:/BirdCipher/Bird_images/Pterocliformes13.png", "C:/BirdCipher/Bird_images/Pterocliformes14.png",
"C:/BirdCipher/Bird_images/Pterocliformes15.png", "C:/BirdCipher/Bird_images/Pterocliformes16.png", "C:/BirdCipher/Bird_images/Pterocliformes17.png",
"C:/BirdCipher/Bird_images/Pterocliformes18.png"], ["C:/BirdCipher/Bird_images/Cuculiformes1.png", "C:/BirdCipher/Bird_images/Cuculiformes2.png",
"C:/BirdCipher/Bird_images/Cuculiformes3.png", "C:/BirdCipher/Bird_images/Cuculiformes4.png", "C:/BirdCipher/Bird_images/Cuculiformes5.png",
"C:/BirdCipher/Bird_images/Cuculiformes6.png", "C:/BirdCipher/Bird_images/Cuculiformes7.png", "C:/BirdCipher/Bird_images/Cuculiformes8.png",
"C:/BirdCipher/Bird_images/Cuculiformes9.png", "C:/BirdCipher/Bird_images/Cuculiformes10.png", "C:/BirdCipher/Bird_images/Cuculiformes11.png",
"C:/BirdCipher/Bird_images/Cuculiformes12.png", "C:/BirdCipher/Bird_images/Cuculiformes13.png", "C:/BirdCipher/Bird_images/Cuculiformes14.png",
"C:/BirdCipher/Bird_images/Cuculiformes15.png", "C:/BirdCipher/Bird_images/Cuculiformes16.png", "C:/BirdCipher/Bird_images/Cuculiformes17.png",
"C:/BirdCipher/Bird_images/Cuculiformes18.png", "C:/BirdCipher/Bird_images/Cuculiformes19.png", "C:/BirdCipher/Bird_images/Cuculiformes20.png",
"C:/BirdCipher/Bird_images/Cuculiformes21.png"], ["C:/BirdCipher/Bird_images/Otidiformes1.png", "C:/BirdCipher/Bird_images/Otidiformes2.png",
"C:/BirdCipher/Bird_images/Otidiformes3.png", "C:/BirdCipher/Bird_images/Otidiformes4.png", "C:/BirdCipher/Bird_images/Otidiformes5.png",
"C:/BirdCipher/Bird_images/Otidiformes6.png", "C:/BirdCipher/Bird_images/Otidiformes7.png", "C:/BirdCipher/Bird_images/Otidiformes8.png",
"C:/BirdCipher/Bird_images/Otidiformes9.png", "C:/BirdCipher/Bird_images/Otidiformes10.png", "C:/BirdCipher/Bird_images/Otidiformes11.png",
"C:/BirdCipher/Bird_images/Otidiformes12.png", "C:/BirdCipher/Bird_images/Otidiformes13.png", "C:/BirdCipher/Bird_images/Otidiformes14.png",
"C:/BirdCipher/Bird_images/Otidiformes15.png", "C:/BirdCipher/Bird_images/Otidiformes16.png", "C:/BirdCipher/Bird_images/Otidiformes17.png"],
["C:/BirdCipher/Bird_images/Musophagiformes1.png", "C:/BirdCipher/Bird_images/Musophagiformes2.png", "C:/BirdCipher/Bird_images/Musophagiformes3.png",
"C:/BirdCipher/Bird_images/Musophagiformes4.png", "C:/BirdCipher/Bird_images/Musophagiformes5.png", "C:/BirdCipher/Bird_images/Musophagiformes6.png",
"C:/BirdCipher/Bird_images/Musophagiformes7.png", "C:/BirdCipher/Bird_images/Musophagiformes8.png", "C:/BirdCipher/Bird_images/Musophagiformes9.png",
"C:/BirdCipher/Bird_images/Musophagiformes10.png", "C:/BirdCipher/Bird_images/Musophagiformes11.png", "C:/BirdCipher/Bird_images/Musophagiformes12.png",
"C:/BirdCipher/Bird_images/Musophagiformes13.png", "C:/BirdCipher/Bird_images/Musophagiformes14.png", "C:/BirdCipher/Bird_images/Musophagiformes15.png",
"C:/BirdCipher/Bird_images/Musophagiformes16.png", "C:/BirdCipher/Bird_images/Musophagiformes17.png", "C:/BirdCipher/Bird_images/Musophagiformes18.png"],
["C:/BirdCipher/Bird_images/Opisthocomiformes1.png", "C:/BirdCipher/Bird_images/Opisthocomiformes2.png", "C:/BirdCipher/Bird_images/Opisthocomiformes3.png",
"C:/BirdCipher/Bird_images/Opisthocomiformes4.png", "C:/BirdCipher/Bird_images/Opisthocomiformes5.png", "C:/BirdCipher/Bird_images/Opisthocomiformes6.png",
"C:/BirdCipher/Bird_images/Opisthocomiformes7.png", "C:/BirdCipher/Bird_images/Opisthocomiformes8.png", "C:/BirdCipher/Bird_images/Opisthocomiformes9.png",
"C:/BirdCipher/Bird_images/Opisthocomiformes10.png"], ["C:/BirdCipher/Bird_images/Gruiformes1.png", "C:/BirdCipher/Bird_images/Gruiformes2.png",
"C:/BirdCipher/Bird_images/Gruiformes3.png", "C:/BirdCipher/Bird_images/Gruiformes4.png", "C:/BirdCipher/Bird_images/Gruiformes5.png",
"C:/BirdCipher/Bird_images/Gruiformes6.png", "C:/BirdCipher/Bird_images/Gruiformes7.png", "C:/BirdCipher/Bird_images/Gruiformes8.png",
"C:/BirdCipher/Bird_images/Gruiformes9.png", "C:/BirdCipher/Bird_images/Gruiformes10.png", "C:/BirdCipher/Bird_images/Gruiformes11.png",
"C:/BirdCipher/Bird_images/Gruiformes12.png", "C:/BirdCipher/Bird_images/Gruiformes13.png", "C:/BirdCipher/Bird_images/Gruiformes14.png",
"C:/BirdCipher/Bird_images/Gruiformes15.png", "C:/BirdCipher/Bird_images/Gruiformes16.png", "C:/BirdCipher/Bird_images/Gruiformes17.png",
"C:/BirdCipher/Bird_images/Gruiformes18.png", "C:/BirdCipher/Bird_images/Gruiformes19.png", "C:/BirdCipher/Bird_images/Gruiformes20.png"],
["C:/BirdCipher/Bird_images/Charadriiformes1.png", "C:/BirdCipher/Bird_images/Charadriiformes2.png", "C:/BirdCipher/Bird_images/Charadriiformes3.png",
"C:/BirdCipher/Bird_images/Charadriiformes4.png", "C:/BirdCipher/Bird_images/Charadriiformes5.png", "C:/BirdCipher/Bird_images/Charadriiformes6.png",
"C:/BirdCipher/Bird_images/Charadriiformes7.png", "C:/BirdCipher/Bird_images/Charadriiformes8.png", "C:/BirdCipher/Bird_images/Charadriiformes9.png",
"C:/BirdCipher/Bird_images/Charadriiformes10.png", "C:/BirdCipher/Bird_images/Charadriiformes11.png", "C:/BirdCipher/Bird_images/Charadriiformes12.png",
"C:/BirdCipher/Bird_images/Charadriiformes13.png", "C:/BirdCipher/Bird_images/Charadriiformes14.png", "C:/BirdCipher/Bird_images/Charadriiformes15.png",
"C:/BirdCipher/Bird_images/Charadriiformes16.png", "C:/BirdCipher/Bird_images/Charadriiformes17.png", "C:/BirdCipher/Bird_images/Charadriiformes18.png",
"C:/BirdCipher/Bird_images/Charadriiformes19.png", "C:/BirdCipher/Bird_images/Charadriiformes20.png"], ["C:/BirdCipher/Bird_images/Caprimulgiformes1.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes2.png", "C:/BirdCipher/Bird_images/Caprimulgiformes3.png", "C:/BirdCipher/Bird_images/Caprimulgiformes4.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes5.png", "C:/BirdCipher/Bird_images/Caprimulgiformes6.png", "C:/BirdCipher/Bird_images/Caprimulgiformes7.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes8.png", "C:/BirdCipher/Bird_images/Caprimulgiformes9.png", "C:/BirdCipher/Bird_images/Caprimulgiformes10.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes11.png", "C:/BirdCipher/Bird_images/Caprimulgiformes12.png", "C:/BirdCipher/Bird_images/Caprimulgiformes13.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes14.png", "C:/BirdCipher/Bird_images/Caprimulgiformes15.png", "C:/BirdCipher/Bird_images/Caprimulgiformes16.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes17.png", "C:/BirdCipher/Bird_images/Caprimulgiformes18.png", "C:/BirdCipher/Bird_images/Caprimulgiformes19.png",
"C:/BirdCipher/Bird_images/Caprimulgiformes20.png", "C:/BirdCipher/Bird_images/Caprimulgiformes21.png"], ["C:/BirdCipher/Bird_images/Nyctibiiformes1.png",
"C:/BirdCipher/Bird_images/Nyctibiiformes2.png", "C:/BirdCipher/Bird_images/Nyctibiiformes3.png", "C:/BirdCipher/Bird_images/Nyctibiiformes4.png",
"C:/BirdCipher/Bird_images/Nyctibiiformes5.png", "C:/BirdCipher/Bird_images/Nyctibiiformes6.png", "C:/BirdCipher/Bird_images/Nyctibiiformes7.png",
"C:/BirdCipher/Bird_images/Nyctibiiformes8.png", "C:/BirdCipher/Bird_images/Nyctibiiformes9.png", "C:/BirdCipher/Bird_images/Nyctibiiformes10.png",
"C:/BirdCipher/Bird_images/Nyctibiiformes11.png", "C:/BirdCipher/Bird_images/Nyctibiiformes12.png"], ["C:/BirdCipher/Bird_images/Steatornithiformes1.png",
"C:/BirdCipher/Bird_images/Steatornithiformes2.png", "C:/BirdCipher/Bird_images/Steatornithiformes3.png", "C:/BirdCipher/Bird_images/Steatornithiformes4.png",
"C:/BirdCipher/Bird_images/Steatornithiformes5.png", "C:/BirdCipher/Bird_images/Steatornithiformes6.png", "C:/BirdCipher/Bird_images/Steatornithiformes7.png",
"C:/BirdCipher/Bird_images/Steatornithiformes8.png", "C:/BirdCipher/Bird_images/Steatornithiformes9.png", "C:/BirdCipher/Bird_images/Steatornithiformes10.png"],
["C:/BirdCipher/Bird_images/Podargiformes1.png", "C:/BirdCipher/Bird_images/Podargiformes2.png", "C:/BirdCipher/Bird_images/Podargiformes3.png",
"C:/BirdCipher/Bird_images/Podargiformes4.png", "C:/BirdCipher/Bird_images/Podargiformes5.png", "C:/BirdCipher/Bird_images/Podargiformes6.png",
"C:/BirdCipher/Bird_images/Podargiformes7.png", "C:/BirdCipher/Bird_images/Podargiformes8.png", "C:/BirdCipher/Bird_images/Podargiformes9.png",
"C:/BirdCipher/Bird_images/Podargiformes10.png", "C:/BirdCipher/Bird_images/Podargiformes11.png", "C:/BirdCipher/Bird_images/Podargiformes12.png",
"C:/BirdCipher/Bird_images/Podargiformes13.png", "C:/BirdCipher/Bird_images/Podargiformes14.png", "C:/BirdCipher/Bird_images/Podargiformes15.png",
"C:/BirdCipher/Bird_images/Podargiformes16.png", "C:/BirdCipher/Bird_images/Podargiformes17.png", "C:/BirdCipher/Bird_images/Podargiformes18.png",
"C:/BirdCipher/Bird_images/Podargiformes19.png", "C:/BirdCipher/Bird_images/Podargiformes20.png"], ["C:/BirdCipher/Bird_images/Aegotheliformes1.png",
"C:/BirdCipher/Bird_images/Aegotheliformes2.png", "C:/BirdCipher/Bird_images/Aegotheliformes3.png", "C:/BirdCipher/Bird_images/Aegotheliformes4.png",
"C:/BirdCipher/Bird_images/Aegotheliformes5.png", "C:/BirdCipher/Bird_images/Aegotheliformes6.png", "C:/BirdCipher/Bird_images/Aegotheliformes7.png",
"C:/BirdCipher/Bird_images/Aegotheliformes8.png", "C:/BirdCipher/Bird_images/Aegotheliformes9.png", "C:/BirdCipher/Bird_images/Aegotheliformes10.png"],
["C:/BirdCipher/Bird_images/Apodiformes1.png", "C:/BirdCipher/Bird_images/Apodiformes2.png", "C:/BirdCipher/Bird_images/Apodiformes3.png",
"C:/BirdCipher/Bird_images/Apodiformes4.png", "C:/BirdCipher/Bird_images/Apodiformes5.png", "C:/BirdCipher/Bird_images/Apodiformes6.png",
"C:/BirdCipher/Bird_images/Apodiformes7.png", "C:/BirdCipher/Bird_images/Apodiformes8.png", "C:/BirdCipher/Bird_images/Apodiformes9.png",
"C:/BirdCipher/Bird_images/Apodiformes10.png", "C:/BirdCipher/Bird_images/Apodiformes11.png", "C:/BirdCipher/Bird_images/Apodiformes12.png",
"C:/BirdCipher/Bird_images/Apodiformes13.png", "C:/BirdCipher/Bird_images/Apodiformes14.png", "C:/BirdCipher/Bird_images/Apodiformes15.png",
"C:/BirdCipher/Bird_images/Apodiformes16.png", "C:/BirdCipher/Bird_images/Apodiformes17.png", "C:/BirdCipher/Bird_images/Apodiformes18.png",
"C:/BirdCipher/Bird_images/Apodiformes19.png", "C:/BirdCipher/Bird_images/Apodiformes20.png", "C:/BirdCipher/Bird_images/Apodiformes21.png",
"C:/BirdCipher/Bird_images/Apodiformes22.png", "C:/BirdCipher/Bird_images/Apodiformes23.png", "C:/BirdCipher/Bird_images/Apodiformes24.png",
"C:/BirdCipher/Bird_images/Apodiformes25.png", "C:/BirdCipher/Bird_images/Apodiformes26.png", "C:/BirdCipher/Bird_images/Apodiformes27.png",
"C:/BirdCipher/Bird_images/Apodiformes28.png", "C:/BirdCipher/Bird_images/Apodiformes29.png", "C:/BirdCipher/Bird_images/Apodiformes30.png",
"C:/BirdCipher/Bird_images/Apodiformes31.png", "C:/BirdCipher/Bird_images/Apodiformes32.png", "C:/BirdCipher/Bird_images/Apodiformes33.png",
"C:/BirdCipher/Bird_images/Apodiformes34.png", "C:/BirdCipher/Bird_images/Apodiformes35.png", "C:/BirdCipher/Bird_images/Apodiformes36.png"],
["C:/BirdCipher/Bird_images/Phaethontiformes1.png", "C:/BirdCipher/Bird_images/Phaethontiformes2.png", "C:/BirdCipher/Bird_images/Phaethontiformes3.png",
"C:/BirdCipher/Bird_images/Phaethontiformes4.png", "C:/BirdCipher/Bird_images/Phaethontiformes5.png", "C:/BirdCipher/Bird_images/Phaethontiformes6.png",
"C:/BirdCipher/Bird_images/Phaethontiformes7.png", "C:/BirdCipher/Bird_images/Phaethontiformes8.png", "C:/BirdCipher/Bird_images/Phaethontiformes9.png",
"C:/BirdCipher/Bird_images/Phaethontiformes10.png", "C:/BirdCipher/Bird_images/Phaethontiformes11.png", "C:/BirdCipher/Bird_images/Phaethontiformes12.png",
"C:/BirdCipher/Bird_images/Phaethontiformes13.png", "C:/BirdCipher/Bird_images/Phaethontiformes14.png", "C:/BirdCipher/Bird_images/Phaethontiformes15.png",
"C:/BirdCipher/Bird_images/Phaethontiformes16.png", "C:/BirdCipher/Bird_images/Phaethontiformes17.png", "C:/BirdCipher/Bird_images/Phaethontiformes18.png",
"C:/BirdCipher/Bird_images/Phaethontiformes19.png", "C:/BirdCipher/Bird_images/Phaethontiformes20.png"], ["C:/BirdCipher/Bird_images/Eurypygiformes1.png",
"C:/BirdCipher/Bird_images/Eurypygiformes2.png", "C:/BirdCipher/Bird_images/Eurypygiformes3.png", "C:/BirdCipher/Bird_images/Eurypygiformes4.png",
"C:/BirdCipher/Bird_images/Eurypygiformes5.png", "C:/BirdCipher/Bird_images/Eurypygiformes6.png", "C:/BirdCipher/Bird_images/Eurypygiformes7.png",
"C:/BirdCipher/Bird_images/Eurypygiformes8.png", "C:/BirdCipher/Bird_images/Eurypygiformes9.png", "C:/BirdCipher/Bird_images/Eurypygiformes10.png",
"C:/BirdCipher/Bird_images/Eurypygiformes11.png", "C:/BirdCipher/Bird_images/Eurypygiformes12.png", "C:/BirdCipher/Bird_images/Eurypygiformes13.png"],
["C:/BirdCipher/Bird_images/Gaviiformes1.png", "C:/BirdCipher/Bird_images/Gaviiformes2.png", "C:/BirdCipher/Bird_images/Gaviiformes3.png",
"C:/BirdCipher/Bird_images/Gaviiformes4.png", "C:/BirdCipher/Bird_images/Gaviiformes5.png", "C:/BirdCipher/Bird_images/Gaviiformes6.png",
"C:/BirdCipher/Bird_images/Gaviiformes7.png", "C:/BirdCipher/Bird_images/Gaviiformes8.png", "C:/BirdCipher/Bird_images/Gaviiformes9.png",
"C:/BirdCipher/Bird_images/Gaviiformes10.png", "C:/BirdCipher/Bird_images/Gaviiformes11.png", "C:/BirdCipher/Bird_images/Gaviiformes12.png",
"C:/BirdCipher/Bird_images/Gaviiformes13.png", "C:/BirdCipher/Bird_images/Gaviiformes14.png", "C:/BirdCipher/Bird_images/Gaviiformes15.png",
"C:/BirdCipher/Bird_images/Gaviiformes16.png", "C:/BirdCipher/Bird_images/Gaviiformes17.png", "C:/BirdCipher/Bird_images/Gaviiformes18.png",
"C:/BirdCipher/Bird_images/Gaviiformes19.png", "C:/BirdCipher/Bird_images/Gaviiformes20.png"], ["C:/BirdCipher/Bird_images/Procellariiformes1.png",
"C:/BirdCipher/Bird_images/Procellariiformes2.png", "C:/BirdCipher/Bird_images/Procellariiformes3.png", "C:/BirdCipher/Bird_images/Procellariiformes4.png",
"C:/BirdCipher/Bird_images/Procellariiformes5.png", "C:/BirdCipher/Bird_images/Procellariiformes6.png", "C:/BirdCipher/Bird_images/Procellariiformes7.png",
"C:/BirdCipher/Bird_images/Procellariiformes8.png", "C:/BirdCipher/Bird_images/Procellariiformes9.png", "C:/BirdCipher/Bird_images/Procellariiformes10.png",
"C:/BirdCipher/Bird_images/Procellariiformes11.png", "C:/BirdCipher/Bird_images/Procellariiformes12.png", "C:/BirdCipher/Bird_images/Procellariiformes13.png",
"C:/BirdCipher/Bird_images/Procellariiformes14.png", "C:/BirdCipher/Bird_images/Procellariiformes15.png", "C:/BirdCipher/Bird_images/Procellariiformes16.png",
"C:/BirdCipher/Bird_images/Procellariiformes17.png", "C:/BirdCipher/Bird_images/Procellariiformes18.png", "C:/BirdCipher/Bird_images/Procellariiformes19.png",
"C:/BirdCipher/Bird_images/Procellariiformes20.png"], ["C:/BirdCipher/Bird_images/Sphenisciformes1.png", "C:/BirdCipher/Bird_images/Sphenisciformes2.png",
"C:/BirdCipher/Bird_images/Sphenisciformes3.png", "C:/BirdCipher/Bird_images/Sphenisciformes4.png", "C:/BirdCipher/Bird_images/Sphenisciformes5.png",
"C:/BirdCipher/Bird_images/Sphenisciformes6.png", "C:/BirdCipher/Bird_images/Sphenisciformes7.png", "C:/BirdCipher/Bird_images/Sphenisciformes8.png",
"C:/BirdCipher/Bird_images/Sphenisciformes9.png", "C:/BirdCipher/Bird_images/Sphenisciformes10.png", "C:/BirdCipher/Bird_images/Sphenisciformes11.png",
"C:/BirdCipher/Bird_images/Sphenisciformes12.png", "C:/BirdCipher/Bird_images/Sphenisciformes13.png", "C:/BirdCipher/Bird_images/Sphenisciformes14.png",
"C:/BirdCipher/Bird_images/Sphenisciformes15.png", "C:/BirdCipher/Bird_images/Sphenisciformes16.png", "C:/BirdCipher/Bird_images/Sphenisciformes17.png",
"C:/BirdCipher/Bird_images/Sphenisciformes18.png", "C:/BirdCipher/Bird_images/Sphenisciformes19.png", "C:/BirdCipher/Bird_images/Sphenisciformes20.png"],
["C:/BirdCipher/Bird_images/Ciconiiformes1.png", "C:/BirdCipher/Bird_images/Ciconiiformes2.png", "C:/BirdCipher/Bird_images/Ciconiiformes3.png",
"C:/BirdCipher/Bird_images/Ciconiiformes4.png", "C:/BirdCipher/Bird_images/Ciconiiformes5.png", "C:/BirdCipher/Bird_images/Ciconiiformes6.png",
"C:/BirdCipher/Bird_images/Ciconiiformes7.png", "C:/BirdCipher/Bird_images/Ciconiiformes8.png", "C:/BirdCipher/Bird_images/Ciconiiformes9.png",
"C:/BirdCipher/Bird_images/Ciconiiformes10.png", "C:/BirdCipher/Bird_images/Ciconiiformes11.png", "C:/BirdCipher/Bird_images/Ciconiiformes12.png",
"C:/BirdCipher/Bird_images/Ciconiiformes13.png", "C:/BirdCipher/Bird_images/Ciconiiformes14.png", "C:/BirdCipher/Bird_images/Ciconiiformes15.png",
"C:/BirdCipher/Bird_images/Ciconiiformes16.png", "C:/BirdCipher/Bird_images/Ciconiiformes17.png", "C:/BirdCipher/Bird_images/Ciconiiformes18.png",
"C:/BirdCipher/Bird_images/Ciconiiformes19.png", "C:/BirdCipher/Bird_images/Ciconiiformes20.png", "C:/BirdCipher/Bird_images/Ciconiiformes21.png"],
["C:/BirdCipher/Bird_images/Suliformes1.png", "C:/BirdCipher/Bird_images/Suliformes2.png", "C:/BirdCipher/Bird_images/Suliformes3.png",
"C:/BirdCipher/Bird_images/Suliformes4.png", "C:/BirdCipher/Bird_images/Suliformes5.png", "C:/BirdCipher/Bird_images/Suliformes6.png",
"C:/BirdCipher/Bird_images/Suliformes7.png", "C:/BirdCipher/Bird_images/Suliformes8.png", "C:/BirdCipher/Bird_images/Suliformes9.png",
"C:/BirdCipher/Bird_images/Suliformes10.png", "C:/BirdCipher/Bird_images/Suliformes11.png", "C:/BirdCipher/Bird_images/Suliformes12.png",
"C:/BirdCipher/Bird_images/Suliformes13.png", "C:/BirdCipher/Bird_images/Suliformes14.png", "C:/BirdCipher/Bird_images/Suliformes15.png",
"C:/BirdCipher/Bird_images/Suliformes16.png", "C:/BirdCipher/Bird_images/Suliformes17.png", "C:/BirdCipher/Bird_images/Suliformes18.png",
"C:/BirdCipher/Bird_images/Suliformes19.png", "C:/BirdCipher/Bird_images/Suliformes20.png", "C:/BirdCipher/Bird_images/Suliformes21.png"],
["C:/BirdCipher/Bird_images/Pelecaniformes1.png", "C:/BirdCipher/Bird_images/Pelecaniformes2.png", "C:/BirdCipher/Bird_images/Pelecaniformes3.png",
"C:/BirdCipher/Bird_images/Pelecaniformes4.png", "C:/BirdCipher/Bird_images/Pelecaniformes5.png", "C:/BirdCipher/Bird_images/Pelecaniformes6.png",
"C:/BirdCipher/Bird_images/Pelecaniformes7.png", "C:/BirdCipher/Bird_images/Pelecaniformes8.png", "C:/BirdCipher/Bird_images/Pelecaniformes9.png",
"C:/BirdCipher/Bird_images/Pelecaniformes10.png", "C:/BirdCipher/Bird_images/Pelecaniformes11.png", "C:/BirdCipher/Bird_images/Pelecaniformes12.png",
"C:/BirdCipher/Bird_images/Pelecaniformes13.png", "C:/BirdCipher/Bird_images/Pelecaniformes14.png", "C:/BirdCipher/Bird_images/Pelecaniformes15.png",
"C:/BirdCipher/Bird_images/Pelecaniformes16.png", "C:/BirdCipher/Bird_images/Pelecaniformes17.png", "C:/BirdCipher/Bird_images/Pelecaniformes18.png",
"C:/BirdCipher/Bird_images/Pelecaniformes19.png", "C:/BirdCipher/Bird_images/Pelecaniformes20.png", "C:/BirdCipher/Bird_images/Pelecaniformes21.png",
"C:/BirdCipher/Bird_images/Pelecaniformes22.png", "C:/BirdCipher/Bird_images/Pelecaniformes23.png", "C:/BirdCipher/Bird_images/Pelecaniformes24.png"],
["C:/BirdCipher/Bird_images/Strigiformes1.png", "C:/BirdCipher/Bird_images/Strigiformes2.png", "C:/BirdCipher/Bird_images/Strigiformes3.png",
"C:/BirdCipher/Bird_images/Strigiformes4.png", "C:/BirdCipher/Bird_images/Strigiformes5.png", "C:/BirdCipher/Bird_images/Strigiformes6.png",
"C:/BirdCipher/Bird_images/Strigiformes7.png", "C:/BirdCipher/Bird_images/Strigiformes8.png", "C:/BirdCipher/Bird_images/Strigiformes9.png",
"C:/BirdCipher/Bird_images/Strigiformes10.png", "C:/BirdCipher/Bird_images/Strigiformes11.png", "C:/BirdCipher/Bird_images/Strigiformes12.png",
"C:/BirdCipher/Bird_images/Strigiformes13.png", "C:/BirdCipher/Bird_images/Strigiformes14.png", "C:/BirdCipher/Bird_images/Strigiformes15.png",
"C:/BirdCipher/Bird_images/Strigiformes16.png", "C:/BirdCipher/Bird_images/Strigiformes17.png", "C:/BirdCipher/Bird_images/Strigiformes18.png",
"C:/BirdCipher/Bird_images/Strigiformes19.png", "C:/BirdCipher/Bird_images/Strigiformes20.png", "C:/BirdCipher/Bird_images/Strigiformes21.png",
"C:/BirdCipher/Bird_images/Strigiformes22.png", "C:/BirdCipher/Bird_images/Strigiformes23.png", "C:/BirdCipher/Bird_images/Strigiformes24.png"],
["C:/BirdCipher/Bird_images/Cathartiformes1.png", "C:/BirdCipher/Bird_images/Cathartiformes2.png", "C:/BirdCipher/Bird_images/Cathartiformes3.png",
"C:/BirdCipher/Bird_images/Cathartiformes4.png", "C:/BirdCipher/Bird_images/Cathartiformes5.png", "C:/BirdCipher/Bird_images/Cathartiformes6.png",
"C:/BirdCipher/Bird_images/Cathartiformes7.png", "C:/BirdCipher/Bird_images/Cathartiformes8.png", "C:/BirdCipher/Bird_images/Cathartiformes9.png",
"C:/BirdCipher/Bird_images/Cathartiformes10.png", "C:/BirdCipher/Bird_images/Cathartiformes11.png", "C:/BirdCipher/Bird_images/Cathartiformes12.png",
"C:/BirdCipher/Bird_images/Cathartiformes13.png", "C:/BirdCipher/Bird_images/Cathartiformes14.png", "C:/BirdCipher/Bird_images/Cathartiformes15.png",
"C:/BirdCipher/Bird_images/Cathartiformes16.png", "C:/BirdCipher/Bird_images/Cathartiformes17.png", "C:/BirdCipher/Bird_images/Cathartiformes18.png",
"C:/BirdCipher/Bird_images/Cathartiformes19.png", "C:/BirdCipher/Bird_images/Cathartiformes20.png"], ["C:/BirdCipher/Bird_images/Accipitriformes1.png",
"C:/BirdCipher/Bird_images/Accipitriformes2.png", "C:/BirdCipher/Bird_images/Accipitriformes3.png", "C:/BirdCipher/Bird_images/Accipitriformes4.png",
"C:/BirdCipher/Bird_images/Accipitriformes5.png", "C:/BirdCipher/Bird_images/Accipitriformes6.png", "C:/BirdCipher/Bird_images/Accipitriformes7.png",
"C:/BirdCipher/Bird_images/Accipitriformes8.png", "C:/BirdCipher/Bird_images/Accipitriformes9.png", "C:/BirdCipher/Bird_images/Accipitriformes10.png",
"C:/BirdCipher/Bird_images/Accipitriformes11.png", "C:/BirdCipher/Bird_images/Accipitriformes12.png", "C:/BirdCipher/Bird_images/Accipitriformes13.png",
"C:/BirdCipher/Bird_images/Accipitriformes14.png", "C:/BirdCipher/Bird_images/Accipitriformes15.png", "C:/BirdCipher/Bird_images/Accipitriformes16.png",
"C:/BirdCipher/Bird_images/Accipitriformes17.png", "C:/BirdCipher/Bird_images/Accipitriformes18.png", "C:/BirdCipher/Bird_images/Accipitriformes19.png",
"C:/BirdCipher/Bird_images/Accipitriformes20.png", "C:/BirdCipher/Bird_images/Accipitriformes21.png", "C:/BirdCipher/Bird_images/Accipitriformes22.png",
"C:/BirdCipher/Bird_images/Accipitriformes23.png", "C:/BirdCipher/Bird_images/Accipitriformes24.png", "C:/BirdCipher/Bird_images/Accipitriformes25.png",
"C:/BirdCipher/Bird_images/Accipitriformes26.png"], ["C:/BirdCipher/Bird_images/Coliiformes1.png", "C:/BirdCipher/Bird_images/Coliiformes2.png",
"C:/BirdCipher/Bird_images/Coliiformes3.png", "C:/BirdCipher/Bird_images/Coliiformes4.png", "C:/BirdCipher/Bird_images/Coliiformes5.png",
"C:/BirdCipher/Bird_images/Coliiformes6.png", "C:/BirdCipher/Bird_images/Coliiformes7.png", "C:/BirdCipher/Bird_images/Coliiformes8.png",
"C:/BirdCipher/Bird_images/Coliiformes9.png", "C:/BirdCipher/Bird_images/Coliiformes10.png", "C:/BirdCipher/Bird_images/Coliiformes11.png",
"C:/BirdCipher/Bird_images/Coliiformes12.png", "C:/BirdCipher/Bird_images/Coliiformes13.png", "C:/BirdCipher/Bird_images/Coliiformes14.png",
"C:/BirdCipher/Bird_images/Coliiformes15.png", "C:/BirdCipher/Bird_images/Coliiformes16.png"], ["C:/BirdCipher/Bird_images/Leptosomiformes1.png",
"C:/BirdCipher/Bird_images/Leptosomiformes2.png", "C:/BirdCipher/Bird_images/Leptosomiformes3.png", "C:/BirdCipher/Bird_images/Leptosomiformes4.png",
"C:/BirdCipher/Bird_images/Leptosomiformes5.png", "C:/BirdCipher/Bird_images/Leptosomiformes6.png", "C:/BirdCipher/Bird_images/Leptosomiformes7.png"],
["C:/BirdCipher/Bird_images/Trogoniformes1.png", "C:/BirdCipher/Bird_images/Trogoniformes2.png", "C:/BirdCipher/Bird_images/Trogoniformes3.png",
"C:/BirdCipher/Bird_images/Trogoniformes4.png", "C:/BirdCipher/Bird_images/Trogoniformes5.png", "C:/BirdCipher/Bird_images/Trogoniformes6.png",
"C:/BirdCipher/Bird_images/Trogoniformes7.png", "C:/BirdCipher/Bird_images/Trogoniformes8.png", "C:/BirdCipher/Bird_images/Trogoniformes9.png",
"C:/BirdCipher/Bird_images/Trogoniformes10.png", "C:/BirdCipher/Bird_images/Trogoniformes11.png", "C:/BirdCipher/Bird_images/Trogoniformes12.png",
"C:/BirdCipher/Bird_images/Trogoniformes13.png", "C:/BirdCipher/Bird_images/Trogoniformes14.png", "C:/BirdCipher/Bird_images/Trogoniformes15.png",
"C:/BirdCipher/Bird_images/Trogoniformes16.png"], ["C:/BirdCipher/Bird_images/Bucerotiformes1.png", "C:/BirdCipher/Bird_images/Bucerotiformes2.png",
"C:/BirdCipher/Bird_images/Bucerotiformes3.png", "C:/BirdCipher/Bird_images/Bucerotiformes4.png", "C:/BirdCipher/Bird_images/Bucerotiformes5.png",
"C:/BirdCipher/Bird_images/Bucerotiformes6.png", "C:/BirdCipher/Bird_images/Bucerotiformes7.png", "C:/BirdCipher/Bird_images/Bucerotiformes8.png",
"C:/BirdCipher/Bird_images/Bucerotiformes9.png", "C:/BirdCipher/Bird_images/Bucerotiformes10.png", "C:/BirdCipher/Bird_images/Bucerotiformes11.png",
"C:/BirdCipher/Bird_images/Bucerotiformes12.png", "C:/BirdCipher/Bird_images/Bucerotiformes13.png", "C:/BirdCipher/Bird_images/Bucerotiformes14.png",
"C:/BirdCipher/Bird_images/Bucerotiformes15.png", "C:/BirdCipher/Bird_images/Bucerotiformes16.png", "C:/BirdCipher/Bird_images/Bucerotiformes17.png",
"C:/BirdCipher/Bird_images/Bucerotiformes18.png", "C:/BirdCipher/Bird_images/Bucerotiformes19.png", "C:/BirdCipher/Bird_images/Bucerotiformes20.png",
"C:/BirdCipher/Bird_images/Bucerotiformes21.png"], ["C:/BirdCipher/Bird_images/Coraciiformes1.png", "C:/BirdCipher/Bird_images/Coraciiformes2.png",
"C:/BirdCipher/Bird_images/Coraciiformes3.png", "C:/BirdCipher/Bird_images/Coraciiformes4.png", "C:/BirdCipher/Bird_images/Coraciiformes5.png",
"C:/BirdCipher/Bird_images/Coraciiformes6.png", "C:/BirdCipher/Bird_images/Coraciiformes7.png", "C:/BirdCipher/Bird_images/Coraciiformes8.png",
"C:/BirdCipher/Bird_images/Coraciiformes9.png", "C:/BirdCipher/Bird_images/Coraciiformes10.png", "C:/BirdCipher/Bird_images/Coraciiformes11.png",
"C:/BirdCipher/Bird_images/Coraciiformes12.png", "C:/BirdCipher/Bird_images/Coraciiformes13.png", "C:/BirdCipher/Bird_images/Coraciiformes14.png",
"C:/BirdCipher/Bird_images/Coraciiformes15.png", "C:/BirdCipher/Bird_images/Coraciiformes16.png", "C:/BirdCipher/Bird_images/Coraciiformes17.png",
"C:/BirdCipher/Bird_images/Coraciiformes18.png", "C:/BirdCipher/Bird_images/Coraciiformes19.png", "C:/BirdCipher/Bird_images/Coraciiformes20.png",
"C:/BirdCipher/Bird_images/Coraciiformes21.png", "C:/BirdCipher/Bird_images/Coraciiformes22.png", "C:/BirdCipher/Bird_images/Coraciiformes23.png",
"C:/BirdCipher/Bird_images/Coraciiformes24.png"], ["C:/BirdCipher/Bird_images/Piciformes1.png", "C:/BirdCipher/Bird_images/Piciformes2.png",
"C:/BirdCipher/Bird_images/Piciformes3.png", "C:/BirdCipher/Bird_images/Piciformes4.png", "C:/BirdCipher/Bird_images/Piciformes5.png",
"C:/BirdCipher/Bird_images/Piciformes6.png", "C:/BirdCipher/Bird_images/Piciformes7.png", "C:/BirdCipher/Bird_images/Piciformes8.png",
"C:/BirdCipher/Bird_images/Piciformes9.png", "C:/BirdCipher/Bird_images/Piciformes10.png", "C:/BirdCipher/Bird_images/Piciformes11.png",
"C:/BirdCipher/Bird_images/Piciformes12.png", "C:/BirdCipher/Bird_images/Piciformes13.png", "C:/BirdCipher/Bird_images/Piciformes14.png",
"C:/BirdCipher/Bird_images/Piciformes15.png", "C:/BirdCipher/Bird_images/Piciformes16.png", "C:/BirdCipher/Bird_images/Piciformes17.png",
"C:/BirdCipher/Bird_images/Piciformes18.png", "C:/BirdCipher/Bird_images/Piciformes19.png", "C:/BirdCipher/Bird_images/Piciformes20.png",
"C:/BirdCipher/Bird_images/Piciformes21.png", "C:/BirdCipher/Bird_images/Piciformes22.png", "C:/BirdCipher/Bird_images/Piciformes23.png",
"C:/BirdCipher/Bird_images/Piciformes24.png", "C:/BirdCipher/Bird_images/Piciformes25.png", "C:/BirdCipher/Bird_images/Piciformes26.png",
"C:/BirdCipher/Bird_images/Piciformes27.png"], ["C:/BirdCipher/Bird_images/Cariamiformes1.png", "C:/BirdCipher/Bird_images/Cariamiformes2.png",
"C:/BirdCipher/Bird_images/Cariamiformes3.png", "C:/BirdCipher/Bird_images/Cariamiformes4.png", "C:/BirdCipher/Bird_images/Cariamiformes5.png", 
"C:/BirdCipher/Bird_images/Cariamiformes6.png", "C:/BirdCipher/Bird_images/Cariamiformes7.png"], ["C:/BirdCipher/Bird_images/Falconiformes1.png",
"C:/BirdCipher/Bird_images/Falconiformes2.png", "C:/BirdCipher/Bird_images/Falconiformes3.png", "C:/BirdCipher/Bird_images/Falconiformes4.png",
"C:/BirdCipher/Bird_images/Falconiformes5.png", "C:/BirdCipher/Bird_images/Falconiformes6.png", "C:/BirdCipher/Bird_images/Falconiformes7.png",
"C:/BirdCipher/Bird_images/Falconiformes8.png", "C:/BirdCipher/Bird_images/Falconiformes9.png", "C:/BirdCipher/Bird_images/Falconiformes10.png",
"C:/BirdCipher/Bird_images/Falconiformes11.png", "C:/BirdCipher/Bird_images/Falconiformes12.png", "C:/BirdCipher/Bird_images/Falconiformes13.png",
"C:/BirdCipher/Bird_images/Falconiformes14.png", "C:/BirdCipher/Bird_images/Falconiformes15.png", "C:/BirdCipher/Bird_images/Falconiformes16.png",
"C:/BirdCipher/Bird_images/Falconiformes17.png", "C:/BirdCipher/Bird_images/Falconiformes18.png", "C:/BirdCipher/Bird_images/Falconiformes19.png",
"C:/BirdCipher/Bird_images/Falconiformes20.png"], ["C:/BirdCipher/Bird_images/Psittaciformes1.png", "C:/BirdCipher/Bird_images/Psittaciformes2.png",
"C:/BirdCipher/Bird_images/Psittaciformes3.png", "C:/BirdCipher/Bird_images/Psittaciformes4.png", "C:/BirdCipher/Bird_images/Psittaciformes5.png",
"C:/BirdCipher/Bird_images/Psittaciformes6.png", "C:/BirdCipher/Bird_images/Psittaciformes7.png", "C:/BirdCipher/Bird_images/Psittaciformes8.png",
"C:/BirdCipher/Bird_images/Psittaciformes9.png", "C:/BirdCipher/Bird_images/Psittaciformes10.png", "C:/BirdCipher/Bird_images/Psittaciformes11.png",
"C:/BirdCipher/Bird_images/Psittaciformes12.png", "C:/BirdCipher/Bird_images/Psittaciformes13.png", "C:/BirdCipher/Bird_images/Psittaciformes14.png",
"C:/BirdCipher/Bird_images/Psittaciformes15.png", "C:/BirdCipher/Bird_images/Psittaciformes16.png", "C:/BirdCipher/Bird_images/Psittaciformes17.png",
"C:/BirdCipher/Bird_images/Psittaciformes18.png", "C:/BirdCipher/Bird_images/Psittaciformes19.png", "C:/BirdCipher/Bird_images/Psittaciformes20.png"],
["C:/BirdCipher/Bird_images/Passeriformes1.png", "C:/BirdCipher/Bird_images/Passeriformes2.png", "C:/BirdCipher/Bird_images/Passeriformes3.png",
"C:/BirdCipher/Bird_images/Passeriformes4.png", "C:/BirdCipher/Bird_images/Passeriformes5.png", "C:/BirdCipher/Bird_images/Passeriformes6.png",
"C:/BirdCipher/Bird_images/Passeriformes7.png", "C:/BirdCipher/Bird_images/Passeriformes8.png", "C:/BirdCipher/Bird_images/Passeriformes9.png",
"C:/BirdCipher/Bird_images/Passeriformes10.png", "C:/BirdCipher/Bird_images/Passeriformes11.png", "C:/BirdCipher/Bird_images/Passeriformes12.png",
"C:/BirdCipher/Bird_images/Passeriformes13.png", "C:/BirdCipher/Bird_images/Passeriformes14.png", "C:/BirdCipher/Bird_images/Passeriformes15.png",
"C:/BirdCipher/Bird_images/Passeriformes16.png", "C:/BirdCipher/Bird_images/Passeriformes17.png", "C:/BirdCipher/Bird_images/Passeriformes18.png",
"C:/BirdCipher/Bird_images/Passeriformes19.png", "C:/BirdCipher/Bird_images/Passeriformes20.png", "C:/BirdCipher/Bird_images/Passeriformes21.png",
"C:/BirdCipher/Bird_images/Passeriformes22.png"]]



number_species = [38, 55, 13, 8, 10, 457, 442, 23, 42, 441, 3, 20, 188, 39, 23, 4, 443, 622, 130, 8, 4, 20, 13, 541, 7, 3, 23, 218,
97, 73, 141, 240, 355, 42, 420, 20, 1, 52, 83, 248, 541, 8, 119, 502, 7715]

bird_songs = ['C:/BirdCipher/Audios/BirdSongs/BirdSong_0.wav', 'C:/BirdCipher/Audios/BirdSongs/BirdSong_1.wav', 'C:/BirdCipher/Audios/BirdSongs/BirdSong_2.wav']


#print(len(BirdCipher_list))